Create a Numpy array filled with all zeros

In [2]:
import numpy as np

In [3]:
a = np.zeros(4, dtype = int) 
print("Matrix a : \n", a) 
  
b = np.zeros([3,2], dtype = int) 
print("\nMatrix b : \n", b) 

Matrix a : 
 [0 0 0 0]

Matrix b : 
 [[0 0]
 [0 0]
 [0 0]]


In [13]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Create a Numpy array filled with all ones

In [4]:
 
a = np.ones(5, dtype = int)
print("Matrix a : \n", a)
 
b =np.ones([4,3], dtype = int)
print("\nMatrix b : \n", b)

Matrix a : 
 [1 1 1 1 1]

Matrix b : 
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [15]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

How to Remove rows in Numpy array that contains non-numeric values?

In [4]:
n_arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])
print(n_arr)

[[10.5 22.5  3.8]
 [41.   nan  nan]]


In [ ]:
np.array([1,2,3])

In [5]:
# Creating 2X3 2-D Numpy array
n_arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])
  
print("Given array:")
print(n_arr)
  
print("\nRemove all rows containing non-numeric elements")
print(n_arr[~np.isnan(n_arr).any(axis=1)])

Given array:
[[10.5 22.5  3.8]
 [41.   nan  nan]]

Remove all rows containing non-numeric elements
[[10.5 22.5  3.8]]


In [9]:
n_arr[~np.isnan(n_arr).any(axis=1)]

array([[10.5, 22.5,  3.8]])

Find the most frequent value in a NumPy array

In [12]:
# create array
x = np.array([1,2,3,4,5,1,2,1,1,1,2,3,2,2,2,2,2])
print("Original array:")
print(x)
  
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[1 2 3 4 5 1 2 1 1 1 2 3 2 2 2 2 2]
Most frequent value in the above array:
2


How to add a border around a NumPy array?

In [12]:
np.bincount(x).argmax()

2

In [16]:
# Creating a 2X2 Numpy matrix
array = np.ones((2, 2))
  
print("Original array")
print(array)
  
print("\n0 on the border and 1 inside the array")
  
# constructing border of 0 around 2D identity matrix
# using np.pad()
array = np.pad(array, pad_width=1,
               constant_values=0)
  
print(array)

Original array
[[1. 1.]
 [1. 1.]]

0 on the border and 1 inside the array
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


How to compare two NumPy arrays?

In [19]:
an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [3, 4]])
 
comparison = an_array == another_array
equal_arrays = comparison.all()
 
print(equal_arrays)

True


How to check whether specified values are present in NumPy array?

In [9]:
# creating a Numpy array
n_array = np.array([[2, 3, 0],
                    [4, 1, 6]])
  
print("Given array:")
print(n_array)
  
# Checking whether specific values
# are present in "n_array" or not
print(2 in n_array)
print(0 in n_array)
print(6 in n_array)
print(50 in n_array)
print(10 in n_array)

Given array:
[[2 3 0]
 [4 1 6]]
True
True
True
False
False


Get the maximum value from given matrix

In [12]:
# make matrix with numpy
gfg = np.matrix('[64, 1; 12, 3]')
          
# applying matrix.min() method
geeks = gfg.max()
print(geeks)

64


In [15]:
a= np.array([1,2,56,87,49])
print(a)
print(a.max())

[ 1  2 56 87 49]
87


Get the minimum value from given matrix

In [12]:
# make matrix with numpy
gfg = np.matrix('[64, 1; 12, 3]')
          
# applying matrix.min() method
geeks = gfg.min()
print(geeks)

1


Select the elements from a given matrix

In [21]:
# make matrix with numpy
gfg = np.matrix('[4, 1, 12, 3, 4, 6, 7]')
              
# applying matrix.take() method
geek = gfg.take(-3)
    
print(geek)

[[4]]


Find the sum of values in a matrix

In [19]:
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
#gfg = np.matrix('[4, 2; 12, 3]')
             
# applying matrix.sum() method
geek = gfg.sum()
   
print(geek)

20


In [20]:
gfg+gfg

matrix([[ 8,  2],
        [24,  6]])

Calculate the sum of the diagonal elements of a NumPy array

In [15]:
# creating a 3X3 Numpy matrix
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the Trace of a matrix
trace = np.trace(n_array)
  
  
print("\nTrace of given 3X3 matrix:")
print(trace)

Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Trace of given 3X3 matrix:
176


In [28]:
55+44+77

176

Adding and Subtracting Matrices in Python

In [29]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [16]:
# creating first matrix
A = np.array([[1, 2], [3, 4]])
  
# creating second matrix
B = np.array([[4, 5], [6, 7]])
  
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
  
# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


In [17]:
# creating first matrix
A = np.array([[1, 2], [3, 4]])
  
# creating second matrix
B = np.array([[4, 5], [6, 7]])
  
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
  
# subtracting two matrix
print("Subtraction of two matrix")
print(np.subtract(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


Matrix Multiplication in NumPy

In [18]:
# creating two matrices
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
print("Matrix p :")
print(p)
print("Matrix q :")
print(q)
  
# computing product
result = np.dot(p, q)

  
# printing the result
print("The matrix multiplication is :")
print(result)

Matrix p :
[[1, 2], [2, 3]]
Matrix q :
[[4, 5], [6, 7]]
The matrix multiplication is :
[[16 19]
 [26 31]]


In [29]:
arr = np.random.randint(1,200,10)
print(arr)

[122  39 153 163 121 154  91 109 154  76]


In [30]:
arr1 = np.random.rand(20)
print(arr1)

[0.80992595 0.42337904 0.77684094 0.02296032 0.0203011  0.77841678
 0.6743515  0.07607785 0.75651745 0.25682195 0.12224147 0.9018244
 0.31103398 0.56800848 0.01096827 0.27508968 0.55205192 0.2932343
 0.98620185 0.18193656]


In [32]:
arr1.reshape(5,4)

array([[0.80992595, 0.42337904, 0.77684094, 0.02296032],
       [0.0203011 , 0.77841678, 0.6743515 , 0.07607785],
       [0.75651745, 0.25682195, 0.12224147, 0.9018244 ],
       [0.31103398, 0.56800848, 0.01096827, 0.27508968],
       [0.55205192, 0.2932343 , 0.98620185, 0.18193656]])

In [33]:
arr1.reshape(2,10)

array([[0.80992595, 0.42337904, 0.77684094, 0.02296032, 0.0203011 ,
        0.77841678, 0.6743515 , 0.07607785, 0.75651745, 0.25682195],
       [0.12224147, 0.9018244 , 0.31103398, 0.56800848, 0.01096827,
        0.27508968, 0.55205192, 0.2932343 , 0.98620185, 0.18193656]])

In [34]:
#a = np.array([10,20,30,40,50,60])
np.linspace(4,6,10)

array([4.        , 4.22222222, 4.44444444, 4.66666667, 4.88888889,
       5.11111111, 5.33333333, 5.55555556, 5.77777778, 6.        ])

In [30]:
 4.22222222 -4

0.22222221999999991

In [31]:
4.44444444- 4.22222222

0.22222221999999991

In [30]:
4.66666667-4.44444444


0.22222222999999985

In [29]:
4.4-4.2

0.20000000000000018

In [36]:
import pandas as pd

In [37]:
df1= pd.read_csv("Advertising.csv")

In [39]:
df1.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [42]:
df1[df1['newspaper']==69.2]

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1

In [43]:
np.where(df1[df1['newspaper']==69.2])

(array([0, 0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3, 4], dtype=int64))